### ISSUE TITLE
String return type instead of object for first node.

### ISSUE THREAD

**Issue by gitRpm** [Firenza/graphql-netstandard-client#14]
I have a little different scenario than the example you provided deserializing the `Repository` object.

Rather than an object being returned as the first node in the request, I am receiving a string along with some additional data in `extensions`:
```
{
   data: {
     token: "stringtoken"
   },
   extensions: {
     runTimeMilliseconds: 9
   }
}
```

Is there a way to parse that using the `GraphQlNodesParentConverter` class?

**Comment by Firenza** [comment]
So that class is just for making collections easily deserializable into .NET.  In your case above you just have a simple JSON object so in order to get that back changed would have to be the following changes would have to be made to the client

1. Add an `Extensions` Property to the response.
2. Allow the sending in of a generic type with which to deserialize the `Extensions` property into.

If you want you can try submitting a PR with these changes or you can wait until I do it.  It will probably be at least a few weeks until I have time.
